language: ruby

cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head

sudo: false

bundler_args: --without development --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
